/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BridgeInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "RELAYER_ROLE()": FunctionFragment;
    "_chainID()": FunctionFragment;
    "_depositCounts(uint8)": FunctionFragment;
    "_depositRecords(uint64,uint8)": FunctionFragment;
    "_expiry()": FunctionFragment;
    "_fee()": FunctionFragment;
    "_hasVotedOnProposal(uint72,bytes32,address)": FunctionFragment;
    "_proposals(uint72,bytes32)": FunctionFragment;
    "_relayerThreshold()": FunctionFragment;
    "_resourceIDToHandlerAddress(bytes32)": FunctionFragment;
    "_specialFee()": FunctionFragment;
    "_specialFeeChainID()": FunctionFragment;
    "_totalProposals()": FunctionFragment;
    "_totalRelayers()": FunctionFragment;
    "_wtokenAddress()": FunctionFragment;
    "adminAddRelayer(address)": FunctionFragment;
    "adminChangeFee(uint256)": FunctionFragment;
    "adminChangeRelayerThreshold(uint256)": FunctionFragment;
    "adminChangeSpecialFee(uint256,uint8)": FunctionFragment;
    "adminPauseTransfers()": FunctionFragment;
    "adminRemoveRelayer(address)": FunctionFragment;
    "adminSetBurnable(address,address)": FunctionFragment;
    "adminSetGenericResource(address,bytes32,address,bytes4,uint256,bytes4)": FunctionFragment;
    "adminSetResource(address,bytes32,address)": FunctionFragment;
    "adminUnpauseTransfers()": FunctionFragment;
    "adminUpdateBridgeAddress(address,address)": FunctionFragment;
    "adminWithdraw(address,address,address,uint256)": FunctionFragment;
    "cancelProposal(uint8,uint64,bytes32)": FunctionFragment;
    "deposit(uint8,bytes32,bytes)": FunctionFragment;
    "depositETH(uint8,bytes32,bytes)": FunctionFragment;
    "executeProposal(uint8,uint64,bytes,bytes32)": FunctionFragment;
    "getFee(uint8)": FunctionFragment;
    "getFees()": FunctionFragment;
    "getProposal(uint8,uint64,bytes32)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getRoleMember(bytes32,uint256)": FunctionFragment;
    "getRoleMemberCount(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isRelayer(address)": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceAdmin(address)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "transferFunds(address[],uint256[])": FunctionFragment;
    "voteProposal(uint8,uint64,bytes32,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_chainID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_depositCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_depositRecords",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "_expiry", values?: undefined): string;
  encodeFunctionData(functionFragment: "_fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_hasVotedOnProposal",
    values: [BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "_proposals",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_relayerThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_resourceIDToHandlerAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_specialFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_specialFeeChainID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_totalProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_totalRelayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_wtokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddRelayer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "adminChangeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminChangeRelayerThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminChangeSpecialFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminPauseTransfers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminRemoveRelayer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetBurnable",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetGenericResource",
    values: [string, BytesLike, string, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetResource",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "adminUnpauseTransfers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminUpdateBridgeAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdraw",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "isRelayer", values: [string]): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceAdmin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFunds",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "voteProposal",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_chainID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_depositCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_depositRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_expiry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_hasVotedOnProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_relayerThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_resourceIDToHandlerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_specialFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_specialFeeChainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_totalProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_totalRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_wtokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminChangeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminChangeRelayerThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminChangeSpecialFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminPauseTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminRemoveRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetBurnable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetGenericResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminUnpauseTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminUpdateBridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRelayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteProposal",
    data: BytesLike
  ): Result;

  events: {
    "Deposit(uint8,bytes32,uint64)": EventFragment;
    "Paused(address)": EventFragment;
    "ProposalEvent(uint8,uint64,uint8,bytes32,bytes32)": EventFragment;
    "ProposalVote(uint8,uint64,uint8,bytes32)": EventFragment;
    "RelayerAdded(address)": EventFragment;
    "RelayerRemoved(address)": EventFragment;
    "RelayerThresholdChanged(uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayerAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayerRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayerThresholdChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export class Bridge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BridgeInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    RELAYER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "RELAYER_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    _chainID(overrides?: CallOverrides): Promise<[number]>;

    "_chainID()"(overrides?: CallOverrides): Promise<[number]>;

    _depositCounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "_depositCounts(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_depositRecords(uint64,uint8)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _expiry(overrides?: CallOverrides): Promise<[BigNumber]>;

    "_expiry()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    _fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    "_fee()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    _hasVotedOnProposal(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "_hasVotedOnProposal(uint72,bytes32,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    _proposals(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, BigNumber] & {
        _resourceID: string;
        _dataHash: string;
        _status: number;
        _proposedBlock: BigNumber;
      }
    >;

    "_proposals(uint72,bytes32)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, BigNumber] & {
        _resourceID: string;
        _dataHash: string;
        _status: number;
        _proposedBlock: BigNumber;
      }
    >;

    _relayerThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    "_relayerThreshold()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    _resourceIDToHandlerAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_resourceIDToHandlerAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _specialFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    "_specialFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    _specialFeeChainID(overrides?: CallOverrides): Promise<[number]>;

    "_specialFeeChainID()"(overrides?: CallOverrides): Promise<[number]>;

    _totalProposals(overrides?: CallOverrides): Promise<[BigNumber]>;

    "_totalProposals()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    _totalRelayers(overrides?: CallOverrides): Promise<[BigNumber]>;

    "_totalRelayers()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    _wtokenAddress(overrides?: CallOverrides): Promise<[string]>;

    "_wtokenAddress()"(overrides?: CallOverrides): Promise<[string]>;

    adminAddRelayer(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminAddRelayer(address)"(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminChangeFee(
      newFee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminChangeFee(uint256)"(
      newFee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminChangeRelayerThreshold(
      newThreshold: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminChangeRelayerThreshold(uint256)"(
      newThreshold: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminChangeSpecialFee(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminChangeSpecialFee(uint256,uint8)"(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminPauseTransfers(overrides?: Overrides): Promise<ContractTransaction>;

    "adminPauseTransfers()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminRemoveRelayer(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminRemoveRelayer(address)"(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminSetBurnable(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminSetBurnable(address,address)"(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminSetGenericResource(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminSetGenericResource(address,bytes32,address,bytes4,uint256,bytes4)"(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminSetResource(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminSetResource(address,bytes32,address)"(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminUnpauseTransfers(overrides?: Overrides): Promise<ContractTransaction>;

    "adminUnpauseTransfers()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminUpdateBridgeAddress(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminUpdateBridgeAddress(address,address)"(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    adminWithdraw(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminWithdraw(address,address,address,uint256)"(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelProposal(uint8,uint64,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    deposit(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "deposit(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    depositETH(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "depositETH(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    executeProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeProposal(uint8,uint64,bytes,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getFee(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getFee(uint8)"(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFees(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, number]>;

    "getFees()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    getProposal(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string[], string[], number, BigNumber] & {
          _resourceID: string;
          _dataHash: string;
          _yesVotes: string[];
          _noVotes: string[];
          _status: number;
          _proposedBlock: BigNumber;
        }
      ]
    >;

    "getProposal(uint8,uint64,bytes32)"(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string[], string[], number, BigNumber] & {
          _resourceID: string;
          _dataHash: string;
          _yesVotes: string[];
          _noVotes: string[];
          _status: number;
          _proposedBlock: BigNumber;
        }
      ]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isRelayer(relayer: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isRelayer(address)"(
      relayer: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    renounceAdmin(
      newAdmin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "renounceAdmin(address)"(
      newAdmin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFunds(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFunds(address[],uint256[])"(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    voteProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "voteProposal(uint8,uint64,bytes32,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  RELAYER_ROLE(overrides?: CallOverrides): Promise<string>;

  "RELAYER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  _chainID(overrides?: CallOverrides): Promise<number>;

  "_chainID()"(overrides?: CallOverrides): Promise<number>;

  _depositCounts(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "_depositCounts(uint8)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _depositRecords(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "_depositRecords(uint64,uint8)"(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  _expiry(overrides?: CallOverrides): Promise<BigNumber>;

  "_expiry()"(overrides?: CallOverrides): Promise<BigNumber>;

  _fee(overrides?: CallOverrides): Promise<BigNumber>;

  "_fee()"(overrides?: CallOverrides): Promise<BigNumber>;

  _hasVotedOnProposal(
    arg0: BigNumberish,
    arg1: BytesLike,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "_hasVotedOnProposal(uint72,bytes32,address)"(
    arg0: BigNumberish,
    arg1: BytesLike,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  _proposals(
    arg0: BigNumberish,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, BigNumber] & {
      _resourceID: string;
      _dataHash: string;
      _status: number;
      _proposedBlock: BigNumber;
    }
  >;

  "_proposals(uint72,bytes32)"(
    arg0: BigNumberish,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, BigNumber] & {
      _resourceID: string;
      _dataHash: string;
      _status: number;
      _proposedBlock: BigNumber;
    }
  >;

  _relayerThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  "_relayerThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

  _resourceIDToHandlerAddress(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "_resourceIDToHandlerAddress(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  _specialFee(overrides?: CallOverrides): Promise<BigNumber>;

  "_specialFee()"(overrides?: CallOverrides): Promise<BigNumber>;

  _specialFeeChainID(overrides?: CallOverrides): Promise<number>;

  "_specialFeeChainID()"(overrides?: CallOverrides): Promise<number>;

  _totalProposals(overrides?: CallOverrides): Promise<BigNumber>;

  "_totalProposals()"(overrides?: CallOverrides): Promise<BigNumber>;

  _totalRelayers(overrides?: CallOverrides): Promise<BigNumber>;

  "_totalRelayers()"(overrides?: CallOverrides): Promise<BigNumber>;

  _wtokenAddress(overrides?: CallOverrides): Promise<string>;

  "_wtokenAddress()"(overrides?: CallOverrides): Promise<string>;

  adminAddRelayer(
    relayerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminAddRelayer(address)"(
    relayerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminChangeFee(
    newFee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminChangeFee(uint256)"(
    newFee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminChangeRelayerThreshold(
    newThreshold: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminChangeRelayerThreshold(uint256)"(
    newThreshold: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminChangeSpecialFee(
    newFee: BigNumberish,
    chainID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminChangeSpecialFee(uint256,uint8)"(
    newFee: BigNumberish,
    chainID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminPauseTransfers(overrides?: Overrides): Promise<ContractTransaction>;

  "adminPauseTransfers()"(overrides?: Overrides): Promise<ContractTransaction>;

  adminRemoveRelayer(
    relayerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminRemoveRelayer(address)"(
    relayerAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminSetBurnable(
    handlerAddress: string,
    tokenAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminSetBurnable(address,address)"(
    handlerAddress: string,
    tokenAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminSetGenericResource(
    handlerAddress: string,
    resourceID: BytesLike,
    contractAddress: string,
    depositFunctionSig: BytesLike,
    depositFunctionDepositerOffset: BigNumberish,
    executeFunctionSig: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminSetGenericResource(address,bytes32,address,bytes4,uint256,bytes4)"(
    handlerAddress: string,
    resourceID: BytesLike,
    contractAddress: string,
    depositFunctionSig: BytesLike,
    depositFunctionDepositerOffset: BigNumberish,
    executeFunctionSig: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminSetResource(
    handlerAddress: string,
    resourceID: BytesLike,
    tokenAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminSetResource(address,bytes32,address)"(
    handlerAddress: string,
    resourceID: BytesLike,
    tokenAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminUnpauseTransfers(overrides?: Overrides): Promise<ContractTransaction>;

  "adminUnpauseTransfers()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminUpdateBridgeAddress(
    handlerAddress: string,
    newBridgeAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminUpdateBridgeAddress(address,address)"(
    handlerAddress: string,
    newBridgeAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  adminWithdraw(
    handlerAddress: string,
    tokenAddress: string,
    recipient: string,
    amountOrTokenID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminWithdraw(address,address,address,uint256)"(
    handlerAddress: string,
    tokenAddress: string,
    recipient: string,
    amountOrTokenID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelProposal(
    chainID: BigNumberish,
    depositNonce: BigNumberish,
    dataHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelProposal(uint8,uint64,bytes32)"(
    chainID: BigNumberish,
    depositNonce: BigNumberish,
    dataHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  deposit(
    destinationChainID: BigNumberish,
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "deposit(uint8,bytes32,bytes)"(
    destinationChainID: BigNumberish,
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  depositETH(
    destinationChainID: BigNumberish,
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "depositETH(uint8,bytes32,bytes)"(
    destinationChainID: BigNumberish,
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  executeProposal(
    chainID: BigNumberish,
    depositNonce: BigNumberish,
    data: BytesLike,
    resourceID: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeProposal(uint8,uint64,bytes,bytes32)"(
    chainID: BigNumberish,
    depositNonce: BigNumberish,
    data: BytesLike,
    resourceID: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getFee(
    destinationChainID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getFee(uint8)"(
    destinationChainID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFees(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, number]>;

  "getFees()"(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, number]>;

  getProposal(
    originChainID: BigNumberish,
    depositNonce: BigNumberish,
    dataHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string[], string[], number, BigNumber] & {
      _resourceID: string;
      _dataHash: string;
      _yesVotes: string[];
      _noVotes: string[];
      _status: number;
      _proposedBlock: BigNumber;
    }
  >;

  "getProposal(uint8,uint64,bytes32)"(
    originChainID: BigNumberish,
    depositNonce: BigNumberish,
    dataHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string[], string[], number, BigNumber] & {
      _resourceID: string;
      _dataHash: string;
      _yesVotes: string[];
      _noVotes: string[];
      _status: number;
      _proposedBlock: BigNumber;
    }
  >;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getRoleAdmin(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMember(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getRoleMember(bytes32,uint256)"(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMemberCount(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getRoleMemberCount(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "grantRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRelayer(relayer: string, overrides?: CallOverrides): Promise<boolean>;

  "isRelayer(address)"(
    relayer: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  renounceAdmin(
    newAdmin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "renounceAdmin(address)"(
    newAdmin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "renounceRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFunds(
    addrs: string[],
    amounts: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFunds(address[],uint256[])"(
    addrs: string[],
    amounts: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  voteProposal(
    chainID: BigNumberish,
    depositNonce: BigNumberish,
    resourceID: BytesLike,
    dataHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "voteProposal(uint8,uint64,bytes32,bytes32)"(
    chainID: BigNumberish,
    depositNonce: BigNumberish,
    resourceID: BytesLike,
    dataHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    RELAYER_ROLE(overrides?: CallOverrides): Promise<string>;

    "RELAYER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    _chainID(overrides?: CallOverrides): Promise<number>;

    "_chainID()"(overrides?: CallOverrides): Promise<number>;

    _depositCounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_depositCounts(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "_depositRecords(uint64,uint8)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    _expiry(overrides?: CallOverrides): Promise<BigNumber>;

    "_expiry()"(overrides?: CallOverrides): Promise<BigNumber>;

    _fee(overrides?: CallOverrides): Promise<BigNumber>;

    "_fee()"(overrides?: CallOverrides): Promise<BigNumber>;

    _hasVotedOnProposal(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "_hasVotedOnProposal(uint72,bytes32,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    _proposals(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, BigNumber] & {
        _resourceID: string;
        _dataHash: string;
        _status: number;
        _proposedBlock: BigNumber;
      }
    >;

    "_proposals(uint72,bytes32)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, BigNumber] & {
        _resourceID: string;
        _dataHash: string;
        _status: number;
        _proposedBlock: BigNumber;
      }
    >;

    _relayerThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    "_relayerThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    _resourceIDToHandlerAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "_resourceIDToHandlerAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    _specialFee(overrides?: CallOverrides): Promise<BigNumber>;

    "_specialFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    _specialFeeChainID(overrides?: CallOverrides): Promise<number>;

    "_specialFeeChainID()"(overrides?: CallOverrides): Promise<number>;

    _totalProposals(overrides?: CallOverrides): Promise<BigNumber>;

    "_totalProposals()"(overrides?: CallOverrides): Promise<BigNumber>;

    _totalRelayers(overrides?: CallOverrides): Promise<BigNumber>;

    "_totalRelayers()"(overrides?: CallOverrides): Promise<BigNumber>;

    _wtokenAddress(overrides?: CallOverrides): Promise<string>;

    "_wtokenAddress()"(overrides?: CallOverrides): Promise<string>;

    adminAddRelayer(
      relayerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminAddRelayer(address)"(
      relayerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adminChangeFee(
      newFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminChangeFee(uint256)"(
      newFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminChangeRelayerThreshold(
      newThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminChangeRelayerThreshold(uint256)"(
      newThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminChangeSpecialFee(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminChangeSpecialFee(uint256,uint8)"(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminPauseTransfers(overrides?: CallOverrides): Promise<void>;

    "adminPauseTransfers()"(overrides?: CallOverrides): Promise<void>;

    adminRemoveRelayer(
      relayerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminRemoveRelayer(address)"(
      relayerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetBurnable(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminSetBurnable(address,address)"(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetGenericResource(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminSetGenericResource(address,bytes32,address,bytes4,uint256,bytes4)"(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetResource(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminSetResource(address,bytes32,address)"(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adminUnpauseTransfers(overrides?: CallOverrides): Promise<void>;

    "adminUnpauseTransfers()"(overrides?: CallOverrides): Promise<void>;

    adminUpdateBridgeAddress(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminUpdateBridgeAddress(address,address)"(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adminWithdraw(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminWithdraw(address,address,address,uint256)"(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelProposal(uint8,uint64,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositETH(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositETH(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executeProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeProposal(uint8,uint64,bytes,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getFee(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getFee(uint8)"(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFees(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, number]>;

    "getFees()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    getProposal(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string[], string[], number, BigNumber] & {
        _resourceID: string;
        _dataHash: string;
        _yesVotes: string[];
        _noVotes: string[];
        _status: number;
        _proposedBlock: BigNumber;
      }
    >;

    "getProposal(uint8,uint64,bytes32)"(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string[], string[], number, BigNumber] & {
        _resourceID: string;
        _dataHash: string;
        _yesVotes: string[];
        _noVotes: string[];
        _status: number;
        _proposedBlock: BigNumber;
      }
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRelayer(relayer: string, overrides?: CallOverrides): Promise<boolean>;

    "isRelayer(address)"(
      relayer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    renounceAdmin(newAdmin: string, overrides?: CallOverrides): Promise<void>;

    "renounceAdmin(address)"(
      newAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferFunds(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "transferFunds(address[],uint256[])"(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    voteProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "voteProposal(uint8,uint64,bytes32,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Deposit(
      destinationChainID: BigNumberish | null,
      resourceID: BytesLike | null,
      depositNonce: BigNumberish | null
    ): TypedEventFilter<
      [number, string, BigNumber],
      {
        destinationChainID: number;
        resourceID: string;
        depositNonce: BigNumber;
      }
    >;

    Paused(account: null): TypedEventFilter<[string], { account: string }>;

    ProposalEvent(
      originChainID: BigNumberish | null,
      depositNonce: BigNumberish | null,
      status: BigNumberish | null,
      resourceID: null,
      dataHash: null
    ): TypedEventFilter<
      [number, BigNumber, number, string, string],
      {
        originChainID: number;
        depositNonce: BigNumber;
        status: number;
        resourceID: string;
        dataHash: string;
      }
    >;

    ProposalVote(
      originChainID: BigNumberish | null,
      depositNonce: BigNumberish | null,
      status: BigNumberish | null,
      resourceID: null
    ): TypedEventFilter<
      [number, BigNumber, number, string],
      {
        originChainID: number;
        depositNonce: BigNumber;
        status: number;
        resourceID: string;
      }
    >;

    RelayerAdded(
      relayer: string | null
    ): TypedEventFilter<[string], { relayer: string }>;

    RelayerRemoved(
      relayer: string | null
    ): TypedEventFilter<[string], { relayer: string }>;

    RelayerThresholdChanged(
      newThreshold: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { newThreshold: BigNumber }>;

    RoleAdminChanged(
      role: BytesLike | null,
      previousAdminRole: BytesLike | null,
      newAdminRole: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleGranted(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    Unpaused(account: null): TypedEventFilter<[string], { account: string }>;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    RELAYER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "RELAYER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    _chainID(overrides?: CallOverrides): Promise<BigNumber>;

    "_chainID()"(overrides?: CallOverrides): Promise<BigNumber>;

    _depositCounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_depositCounts(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_depositRecords(uint64,uint8)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _expiry(overrides?: CallOverrides): Promise<BigNumber>;

    "_expiry()"(overrides?: CallOverrides): Promise<BigNumber>;

    _fee(overrides?: CallOverrides): Promise<BigNumber>;

    "_fee()"(overrides?: CallOverrides): Promise<BigNumber>;

    _hasVotedOnProposal(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_hasVotedOnProposal(uint72,bytes32,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _proposals(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_proposals(uint72,bytes32)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _relayerThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    "_relayerThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    _resourceIDToHandlerAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_resourceIDToHandlerAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _specialFee(overrides?: CallOverrides): Promise<BigNumber>;

    "_specialFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    _specialFeeChainID(overrides?: CallOverrides): Promise<BigNumber>;

    "_specialFeeChainID()"(overrides?: CallOverrides): Promise<BigNumber>;

    _totalProposals(overrides?: CallOverrides): Promise<BigNumber>;

    "_totalProposals()"(overrides?: CallOverrides): Promise<BigNumber>;

    _totalRelayers(overrides?: CallOverrides): Promise<BigNumber>;

    "_totalRelayers()"(overrides?: CallOverrides): Promise<BigNumber>;

    _wtokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "_wtokenAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    adminAddRelayer(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminAddRelayer(address)"(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminChangeFee(
      newFee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminChangeFee(uint256)"(
      newFee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminChangeRelayerThreshold(
      newThreshold: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminChangeRelayerThreshold(uint256)"(
      newThreshold: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminChangeSpecialFee(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminChangeSpecialFee(uint256,uint8)"(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminPauseTransfers(overrides?: Overrides): Promise<BigNumber>;

    "adminPauseTransfers()"(overrides?: Overrides): Promise<BigNumber>;

    adminRemoveRelayer(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminRemoveRelayer(address)"(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminSetBurnable(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminSetBurnable(address,address)"(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminSetGenericResource(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminSetGenericResource(address,bytes32,address,bytes4,uint256,bytes4)"(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminSetResource(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminSetResource(address,bytes32,address)"(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminUnpauseTransfers(overrides?: Overrides): Promise<BigNumber>;

    "adminUnpauseTransfers()"(overrides?: Overrides): Promise<BigNumber>;

    adminUpdateBridgeAddress(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminUpdateBridgeAddress(address,address)"(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    adminWithdraw(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminWithdraw(address,address,address,uint256)"(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelProposal(uint8,uint64,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    deposit(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "deposit(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    depositETH(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "depositETH(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    executeProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeProposal(uint8,uint64,bytes,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getFee(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getFee(uint8)"(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFees(overrides?: CallOverrides): Promise<BigNumber>;

    "getFees()"(overrides?: CallOverrides): Promise<BigNumber>;

    getProposal(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getProposal(uint8,uint64,bytes32)"(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRelayer(relayer: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isRelayer(address)"(
      relayer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceAdmin(newAdmin: string, overrides?: Overrides): Promise<BigNumber>;

    "renounceAdmin(address)"(
      newAdmin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFunds(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFunds(address[],uint256[])"(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    voteProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "voteProposal(uint8,uint64,bytes32,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    RELAYER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "RELAYER_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _chainID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_chainID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _depositCounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_depositCounts(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_depositRecords(uint64,uint8)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _expiry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_expiry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_fee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _hasVotedOnProposal(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_hasVotedOnProposal(uint72,bytes32,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _proposals(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_proposals(uint72,bytes32)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _relayerThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_relayerThreshold()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _resourceIDToHandlerAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_resourceIDToHandlerAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _specialFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_specialFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _specialFeeChainID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_specialFeeChainID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _totalProposals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_totalProposals()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _totalRelayers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_totalRelayers()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _wtokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_wtokenAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    adminAddRelayer(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminAddRelayer(address)"(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminChangeFee(
      newFee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminChangeFee(uint256)"(
      newFee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminChangeRelayerThreshold(
      newThreshold: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminChangeRelayerThreshold(uint256)"(
      newThreshold: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminChangeSpecialFee(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminChangeSpecialFee(uint256,uint8)"(
      newFee: BigNumberish,
      chainID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminPauseTransfers(overrides?: Overrides): Promise<PopulatedTransaction>;

    "adminPauseTransfers()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminRemoveRelayer(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminRemoveRelayer(address)"(
      relayerAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminSetBurnable(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminSetBurnable(address,address)"(
      handlerAddress: string,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminSetGenericResource(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminSetGenericResource(address,bytes32,address,bytes4,uint256,bytes4)"(
      handlerAddress: string,
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminSetResource(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminSetResource(address,bytes32,address)"(
      handlerAddress: string,
      resourceID: BytesLike,
      tokenAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminUnpauseTransfers(overrides?: Overrides): Promise<PopulatedTransaction>;

    "adminUnpauseTransfers()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminUpdateBridgeAddress(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminUpdateBridgeAddress(address,address)"(
      handlerAddress: string,
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    adminWithdraw(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminWithdraw(address,address,address,uint256)"(
      handlerAddress: string,
      tokenAddress: string,
      recipient: string,
      amountOrTokenID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelProposal(uint8,uint64,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    deposit(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "deposit(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    depositETH(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "depositETH(uint8,bytes32,bytes)"(
      destinationChainID: BigNumberish,
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    executeProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeProposal(uint8,uint64,bytes,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      data: BytesLike,
      resourceID: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getFee(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFee(uint8)"(
      destinationChainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFees()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProposal(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getProposal(uint8,uint64,bytes32)"(
      originChainID: BigNumberish,
      depositNonce: BigNumberish,
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRelayer(
      relayer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isRelayer(address)"(
      relayer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceAdmin(
      newAdmin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "renounceAdmin(address)"(
      newAdmin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFunds(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFunds(address[],uint256[])"(
      addrs: string[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    voteProposal(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "voteProposal(uint8,uint64,bytes32,bytes32)"(
      chainID: BigNumberish,
      depositNonce: BigNumberish,
      resourceID: BytesLike,
      dataHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
