/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GenericHandlerInterface extends ethers.utils.Interface {
  functions: {
    "_bridgeAddress()": FunctionFragment;
    "_contractAddressToDepositFunctionDepositerOffset(address)": FunctionFragment;
    "_contractAddressToDepositFunctionSignature(address)": FunctionFragment;
    "_contractAddressToExecuteFunctionSignature(address)": FunctionFragment;
    "_contractAddressToResourceID(address)": FunctionFragment;
    "_contractWhitelist(address)": FunctionFragment;
    "_depositRecords(uint8,uint64)": FunctionFragment;
    "_resourceIDToContractAddress(bytes32)": FunctionFragment;
    "deposit(bytes32,uint8,uint64,address,bytes)": FunctionFragment;
    "executeProposal(bytes32,bytes)": FunctionFragment;
    "getDepositRecord(uint64,uint8)": FunctionFragment;
    "setResource(bytes32,address,bytes4,uint256,bytes4)": FunctionFragment;
    "updateBridgeAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_bridgeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_contractAddressToDepositFunctionDepositerOffset",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_contractAddressToDepositFunctionSignature",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_contractAddressToExecuteFunctionSignature",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_contractAddressToResourceID",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_contractWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_depositRecords",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_resourceIDToContractAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BigNumberish, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositRecord",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setResource",
    values: [BytesLike, string, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBridgeAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_bridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_contractAddressToDepositFunctionDepositerOffset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_contractAddressToDepositFunctionSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_contractAddressToExecuteFunctionSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_contractAddressToResourceID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_contractWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_depositRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_resourceIDToContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBridgeAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class GenericHandler extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GenericHandlerInterface;

  functions: {
    _bridgeAddress(overrides?: CallOverrides): Promise<[string]>;

    "_bridgeAddress()"(overrides?: CallOverrides): Promise<[string]>;

    _contractAddressToDepositFunctionDepositerOffset(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "_contractAddressToDepositFunctionDepositerOffset(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _contractAddressToDepositFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_contractAddressToDepositFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _contractAddressToExecuteFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_contractAddressToExecuteFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _contractAddressToResourceID(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_contractAddressToResourceID(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _contractWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "_contractWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, string, string, string] & {
        _destinationChainID: number;
        _depositer: string;
        _resourceID: string;
        _metaData: string;
      }
    >;

    "_depositRecords(uint8,uint64)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, string, string, string] & {
        _destinationChainID: number;
        _depositer: string;
        _resourceID: string;
        _metaData: string;
      }
    >;

    _resourceIDToContractAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_resourceIDToContractAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getDepositRecord(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, string, string, string] & {
          _destinationChainID: number;
          _depositer: string;
          _resourceID: string;
          _metaData: string;
        }
      ]
    >;

    "getDepositRecord(uint64,uint8)"(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, string, string, string] & {
          _destinationChainID: number;
          _depositer: string;
          _resourceID: string;
          _metaData: string;
        }
      ]
    >;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setResource(bytes32,address,bytes4,uint256,bytes4)"(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateBridgeAddress(
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateBridgeAddress(address)"(
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  _bridgeAddress(overrides?: CallOverrides): Promise<string>;

  "_bridgeAddress()"(overrides?: CallOverrides): Promise<string>;

  _contractAddressToDepositFunctionDepositerOffset(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "_contractAddressToDepositFunctionDepositerOffset(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _contractAddressToDepositFunctionSignature(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "_contractAddressToDepositFunctionSignature(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  _contractAddressToExecuteFunctionSignature(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "_contractAddressToExecuteFunctionSignature(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  _contractAddressToResourceID(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "_contractAddressToResourceID(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  _contractWhitelist(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "_contractWhitelist(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  _depositRecords(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, string, string, string] & {
      _destinationChainID: number;
      _depositer: string;
      _resourceID: string;
      _metaData: string;
    }
  >;

  "_depositRecords(uint8,uint64)"(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, string, string, string] & {
      _destinationChainID: number;
      _depositer: string;
      _resourceID: string;
      _metaData: string;
    }
  >;

  _resourceIDToContractAddress(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "_resourceIDToContractAddress(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  deposit(
    resourceID: BytesLike,
    destinationChainID: BigNumberish,
    depositNonce: BigNumberish,
    depositer: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deposit(bytes32,uint8,uint64,address,bytes)"(
    resourceID: BytesLike,
    destinationChainID: BigNumberish,
    depositNonce: BigNumberish,
    depositer: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeProposal(
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeProposal(bytes32,bytes)"(
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getDepositRecord(
    depositNonce: BigNumberish,
    destId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, string, string, string] & {
      _destinationChainID: number;
      _depositer: string;
      _resourceID: string;
      _metaData: string;
    }
  >;

  "getDepositRecord(uint64,uint8)"(
    depositNonce: BigNumberish,
    destId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, string, string, string] & {
      _destinationChainID: number;
      _depositer: string;
      _resourceID: string;
      _metaData: string;
    }
  >;

  setResource(
    resourceID: BytesLike,
    contractAddress: string,
    depositFunctionSig: BytesLike,
    depositFunctionDepositerOffset: BigNumberish,
    executeFunctionSig: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setResource(bytes32,address,bytes4,uint256,bytes4)"(
    resourceID: BytesLike,
    contractAddress: string,
    depositFunctionSig: BytesLike,
    depositFunctionDepositerOffset: BigNumberish,
    executeFunctionSig: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateBridgeAddress(
    newBridgeAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateBridgeAddress(address)"(
    newBridgeAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    _bridgeAddress(overrides?: CallOverrides): Promise<string>;

    "_bridgeAddress()"(overrides?: CallOverrides): Promise<string>;

    _contractAddressToDepositFunctionDepositerOffset(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_contractAddressToDepositFunctionDepositerOffset(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _contractAddressToDepositFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "_contractAddressToDepositFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    _contractAddressToExecuteFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "_contractAddressToExecuteFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    _contractAddressToResourceID(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "_contractAddressToResourceID(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    _contractWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "_contractWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, string, string, string] & {
        _destinationChainID: number;
        _depositer: string;
        _resourceID: string;
        _metaData: string;
      }
    >;

    "_depositRecords(uint8,uint64)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, string, string, string] & {
        _destinationChainID: number;
        _depositer: string;
        _resourceID: string;
        _metaData: string;
      }
    >;

    _resourceIDToContractAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "_resourceIDToContractAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getDepositRecord(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, string, string, string] & {
        _destinationChainID: number;
        _depositer: string;
        _resourceID: string;
        _metaData: string;
      }
    >;

    "getDepositRecord(uint64,uint8)"(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, string, string, string] & {
        _destinationChainID: number;
        _depositer: string;
        _resourceID: string;
        _metaData: string;
      }
    >;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "setResource(bytes32,address,bytes4,uint256,bytes4)"(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBridgeAddress(
      newBridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateBridgeAddress(address)"(
      newBridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    _bridgeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "_bridgeAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    _contractAddressToDepositFunctionDepositerOffset(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_contractAddressToDepositFunctionDepositerOffset(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _contractAddressToDepositFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_contractAddressToDepositFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _contractAddressToExecuteFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_contractAddressToExecuteFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _contractAddressToResourceID(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_contractAddressToResourceID(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _contractWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_contractWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_depositRecords(uint8,uint64)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _resourceIDToContractAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_resourceIDToContractAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getDepositRecord(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDepositRecord(uint64,uint8)"(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setResource(bytes32,address,bytes4,uint256,bytes4)"(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateBridgeAddress(
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateBridgeAddress(address)"(
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _bridgeAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_bridgeAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _contractAddressToDepositFunctionDepositerOffset(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_contractAddressToDepositFunctionDepositerOffset(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _contractAddressToDepositFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_contractAddressToDepositFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _contractAddressToExecuteFunctionSignature(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_contractAddressToExecuteFunctionSignature(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _contractAddressToResourceID(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_contractAddressToResourceID(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _contractWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_contractWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _depositRecords(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_depositRecords(uint8,uint64)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _resourceIDToContractAddress(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_resourceIDToContractAddress(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getDepositRecord(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDepositRecord(uint64,uint8)"(
      depositNonce: BigNumberish,
      destId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setResource(bytes32,address,bytes4,uint256,bytes4)"(
      resourceID: BytesLike,
      contractAddress: string,
      depositFunctionSig: BytesLike,
      depositFunctionDepositerOffset: BigNumberish,
      executeFunctionSig: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateBridgeAddress(
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateBridgeAddress(address)"(
      newBridgeAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
